
openapi: 3.0.0
info:
  title: CT Factory API
  description: API documentation for the CT Factory system.
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /api/customers:
    get:
      summary: Get all customers
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
    post:
      summary: Add a new customer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Customer created
  /api/orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    product:
                      type: string
                    quantity:
                      type: integer
    post:
      summary: Add a new order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: string
                quantity:
                  type: integer
      responses:
        '201':
          description: Order created
  /api/products:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
    post:
      summary: Add a new product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '201':
          description: Product created
